wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    code_path: code/carla_driver.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1667738789.871626
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.7.0
      5: 0.13.4
      8:
      - 3
      - 5
cuda:
  desc: null
  value: true
env_name:
  desc: null
  value: carla
exp_name:
  desc: null
  value: ddqn
learning_rate:
  desc: null
  value: null
seed:
  desc: null
  value: 0
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 10000
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: idreesrazak
wandb_project_name:
  desc: null
  value: autonomous driving
